FROM postgres:14

ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres
ENV POSTGRES_DB prova

COPY ./create.sql /docker-entrypoint-initdb.d/

ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres
ENV POSTGRES_DB prova_tests

COPY ./create_sql_tests.sql /docker-entrypoint-initdb.d/